// Generated by CoffeeScript 1.9.1
(function() {
  var cl, mysql, mysqlDB;

  cl = console.log;

  mysql = require('mysql');

  mysqlDB = mysql.createConnection({
    host: 'localhost',
    port: '3306',
    user: 'dh',
    password: 'ehdgo170',
    database: 'dh'
  });

  mysqlDB.connect(function(err) {
    return cl((err != null ? err.message : void 0) || 'success');
  });

  mysqlDB.query('select * from TEST_TABLE;', function(err, rows, fields) {
    return cl(err || rows);
  });

  mysqlDB.end();

}).call(this);
