// Generated by CoffeeScript 1.9.1
(function() {
  var cl, config, mssql;

  cl = console.log;

  mssql = require('mssql');

  config = {
    user: 'samUser',
    password: '!@#User',
    server: '152.99.147.11',
    port: '1433',
    database: 'samcheok_2009'
  };

  mssql.connect(config).then(function() {
    return new mssql.Request().query('select count(*) from DUAL').then(function(recordset) {
      cl('recordset');
      cl(recordset);
      return mssql.close();
    })["catch"](function(err) {
      cl('err');
      cl(err.toString());
      return mssql.close();
    });
  })["catch"](function(err) {
    cl(err.toString());
    return mssql.close();
  });

}).call(this);
